/*
Copyright 2025 Mirantis IT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	cephpelagialcmv1alpha1 "github.com/Mirantis/pelagia/pkg/apis/ceph.pelagia.lcm/v1alpha1"
	versioned "github.com/Mirantis/pelagia/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Mirantis/pelagia/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/Mirantis/pelagia/pkg/client/listers/ceph.pelagia.lcm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CephDeploymentSecretInformer provides access to a shared informer and lister for
// CephDeploymentSecrets.
type CephDeploymentSecretInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CephDeploymentSecretLister
}

type cephDeploymentSecretInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCephDeploymentSecretInformer constructs a new informer for CephDeploymentSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCephDeploymentSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCephDeploymentSecretInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCephDeploymentSecretInformer constructs a new informer for CephDeploymentSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCephDeploymentSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LcmV1alpha1().CephDeploymentSecrets(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LcmV1alpha1().CephDeploymentSecrets(namespace).Watch(context.TODO(), options)
			},
		},
		&cephpelagialcmv1alpha1.CephDeploymentSecret{},
		resyncPeriod,
		indexers,
	)
}

func (f *cephDeploymentSecretInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCephDeploymentSecretInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cephDeploymentSecretInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cephpelagialcmv1alpha1.CephDeploymentSecret{}, f.defaultInformer)
}

func (f *cephDeploymentSecretInformer) Lister() v1alpha1.CephDeploymentSecretLister {
	return v1alpha1.NewCephDeploymentSecretLister(f.Informer().GetIndexer())
}
