/*
Copyright 2025 Mirantis IT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	cephpelagialcmv1alpha1 "github.com/Mirantis/pelagia/pkg/apis/ceph.pelagia.lcm/v1alpha1"
	versioned "github.com/Mirantis/pelagia/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Mirantis/pelagia/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/Mirantis/pelagia/pkg/client/listers/ceph.pelagia.lcm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CephDeploymentHealthInformer provides access to a shared informer and lister for
// CephDeploymentHealths.
type CephDeploymentHealthInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CephDeploymentHealthLister
}

type cephDeploymentHealthInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCephDeploymentHealthInformer constructs a new informer for CephDeploymentHealth type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCephDeploymentHealthInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCephDeploymentHealthInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCephDeploymentHealthInformer constructs a new informer for CephDeploymentHealth type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCephDeploymentHealthInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LcmV1alpha1().CephDeploymentHealths(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LcmV1alpha1().CephDeploymentHealths(namespace).Watch(context.TODO(), options)
			},
		},
		&cephpelagialcmv1alpha1.CephDeploymentHealth{},
		resyncPeriod,
		indexers,
	)
}

func (f *cephDeploymentHealthInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCephDeploymentHealthInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cephDeploymentHealthInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cephpelagialcmv1alpha1.CephDeploymentHealth{}, f.defaultInformer)
}

func (f *cephDeploymentHealthInformer) Lister() v1alpha1.CephDeploymentHealthLister {
	return v1alpha1.NewCephDeploymentHealthLister(f.Informer().GetIndexer())
}
