{{ if .Values.rookConfig.volumeSnapshotsEnabled }}
# keep resources for upgrade for backward compatibility
# but do not create them for new setups
# since they will be managed by Pelagia controller now
  {{- $existRbdDriver := lookup "csi.ceph.io/v1" "Driver" "rook-ceph" "rook-ceph.rbd.csi.ceph.com" }}
  {{- if $existRbdDriver }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-rbdplugin-snapclass
  annotations:
    # going to be managed by pelagia
    helm.sh/resource-policy: keep
driver: rook-ceph.rbd.csi.ceph.com # driver:namespace:operator
parameters:
  clusterID: rook-ceph # namespace:cluster
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph # namespace:cluster
deletionPolicy: Delete
  {{ end }}
  {{- $existCephFSDriver := lookup "csi.ceph.io/v1" "Driver" "rook-ceph" "rook-ceph.cephfs.csi.ceph.com" }}
  {{ if $existCephFSDriver }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-cephfsplugin-snapclass
  annotations:
    # going to be managed by pelagia
    helm.sh/resource-policy: keep
driver: rook-ceph.cephfs.csi.ceph.com # driver:namespace:operator
parameters:
  clusterID: rook-ceph # namespace:cluster
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph # namespace:cluster
deletionPolicy: Delete
  {{ end }}
{{ end }}
