version: "2"
linters:
  enable:
    - revive
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
    - linters: [staticcheck]
      text: 'QF1012'
    #  - linters: [staticcheck]
    #    text: 'SA1019:' # deprecated methods required to be replaced
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Mirantis/pelagia
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
