---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-controller-manager
  namespace: {{ .Values.csiOperatorConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
