{{- if eq .Values.productSetup "mke" }}
---
# required for MKE since pelagia controller makes action around deployments and daemonset
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "chart.labels" $ | indent 4}}
  name: {{ .Values.controllers.lcm.account.name }}-{{ template "release.namespace" . }}:cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controllers.lcm.account.name }}
    namespace: {{ template "release.namespace" . }}
  {{- if (.Values.cephDeployment.enabled) }}
---
# required for MKE since pelagia controller makes action around deployments and daemonset
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "chart.labels" $ | indent 4}}
  name: {{ .Values.controllers.cephdeployment.account.name }}-{{ template "release.namespace" . }}:cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controllers.cephdeployment.account.name }}
    namespace: {{ template "release.namespace" . }}
  {{- end }}
---
  {{- if .Values.mkeClusterAdminRole }}
# required for MKE https://mirantis.jira.com/browse/MKE-7825
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:controller:generic-garbage-collector:cluster-admin
  labels:
{{ include "chart.labels" $ | indent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: generic-garbage-collector
  namespace: kube-system
  {{- end }}
{{- end }}
