/*
Copyright 2025 Mirantis IT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1alpha1 "github.com/Mirantis/pelagia/pkg/apis/ceph.pelagia.lcm/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=lcm.mirantis.com, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("cephdeployments"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Lcm().V1alpha1().CephDeployments().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("cephdeploymenthealths"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Lcm().V1alpha1().CephDeploymentHealths().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("cephdeploymentmaintenances"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Lcm().V1alpha1().CephDeploymentMaintenances().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("cephdeploymentsecrets"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Lcm().V1alpha1().CephDeploymentSecrets().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("cephosdremovetasks"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Lcm().V1alpha1().CephOsdRemoveTasks().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
