{{ if and .Values.cephDeployment.netpolEnabled .Values.rookConfig.configureRook }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rook-ceph-operator-policy
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  ingress:
  - ports:
    - port: 9443
      protocol: TCP
  podSelector:
    matchLabels:
      app: rook-ceph-operator
  policyTypes:
  - Ingress
{{ end }}
