/*
Copyright 2025 Mirantis IT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Mirantis/pelagia/pkg/apis/ceph.pelagia.lcm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCephOsdRemoveTasks implements CephOsdRemoveTaskInterface
type FakeCephOsdRemoveTasks struct {
	Fake *FakeLcmV1alpha1
	ns   string
}

var cephosdremovetasksResource = v1alpha1.SchemeGroupVersion.WithResource("cephosdremovetasks")

var cephosdremovetasksKind = v1alpha1.SchemeGroupVersion.WithKind("CephOsdRemoveTask")

// Get takes name of the cephOsdRemoveTask, and returns the corresponding cephOsdRemoveTask object, and an error if there is any.
func (c *FakeCephOsdRemoveTasks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CephOsdRemoveTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cephosdremovetasksResource, c.ns, name), &v1alpha1.CephOsdRemoveTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CephOsdRemoveTask), err
}

// List takes label and field selectors, and returns the list of CephOsdRemoveTasks that match those selectors.
func (c *FakeCephOsdRemoveTasks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CephOsdRemoveTaskList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cephosdremovetasksResource, cephosdremovetasksKind, c.ns, opts), &v1alpha1.CephOsdRemoveTaskList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CephOsdRemoveTaskList{ListMeta: obj.(*v1alpha1.CephOsdRemoveTaskList).ListMeta}
	for _, item := range obj.(*v1alpha1.CephOsdRemoveTaskList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cephOsdRemoveTasks.
func (c *FakeCephOsdRemoveTasks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cephosdremovetasksResource, c.ns, opts))

}

// Create takes the representation of a cephOsdRemoveTask and creates it.  Returns the server's representation of the cephOsdRemoveTask, and an error, if there is any.
func (c *FakeCephOsdRemoveTasks) Create(ctx context.Context, cephOsdRemoveTask *v1alpha1.CephOsdRemoveTask, opts v1.CreateOptions) (result *v1alpha1.CephOsdRemoveTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cephosdremovetasksResource, c.ns, cephOsdRemoveTask), &v1alpha1.CephOsdRemoveTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CephOsdRemoveTask), err
}

// Update takes the representation of a cephOsdRemoveTask and updates it. Returns the server's representation of the cephOsdRemoveTask, and an error, if there is any.
func (c *FakeCephOsdRemoveTasks) Update(ctx context.Context, cephOsdRemoveTask *v1alpha1.CephOsdRemoveTask, opts v1.UpdateOptions) (result *v1alpha1.CephOsdRemoveTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cephosdremovetasksResource, c.ns, cephOsdRemoveTask), &v1alpha1.CephOsdRemoveTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CephOsdRemoveTask), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCephOsdRemoveTasks) UpdateStatus(ctx context.Context, cephOsdRemoveTask *v1alpha1.CephOsdRemoveTask, opts v1.UpdateOptions) (*v1alpha1.CephOsdRemoveTask, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cephosdremovetasksResource, "status", c.ns, cephOsdRemoveTask), &v1alpha1.CephOsdRemoveTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CephOsdRemoveTask), err
}

// Delete takes name of the cephOsdRemoveTask and deletes it. Returns an error if one occurs.
func (c *FakeCephOsdRemoveTasks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(cephosdremovetasksResource, c.ns, name, opts), &v1alpha1.CephOsdRemoveTask{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCephOsdRemoveTasks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cephosdremovetasksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CephOsdRemoveTaskList{})
	return err
}

// Patch applies the patch and returns the patched cephOsdRemoveTask.
func (c *FakeCephOsdRemoveTasks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CephOsdRemoveTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cephosdremovetasksResource, c.ns, name, pt, data, subresources...), &v1alpha1.CephOsdRemoveTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CephOsdRemoveTask), err
}
