/*
Copyright 2026 Mirantis IT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/Mirantis/pelagia/pkg/apis/ceph.pelagia.lcm/v1alpha1"
	cephpelagialcmv1alpha1 "github.com/Mirantis/pelagia/pkg/client/clientset/versioned/typed/ceph.pelagia.lcm/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCephDeploymentSecrets implements CephDeploymentSecretInterface
type fakeCephDeploymentSecrets struct {
	*gentype.FakeClientWithList[*v1alpha1.CephDeploymentSecret, *v1alpha1.CephDeploymentSecretList]
	Fake *FakeLcmV1alpha1
}

func newFakeCephDeploymentSecrets(fake *FakeLcmV1alpha1, namespace string) cephpelagialcmv1alpha1.CephDeploymentSecretInterface {
	return &fakeCephDeploymentSecrets{
		gentype.NewFakeClientWithList[*v1alpha1.CephDeploymentSecret, *v1alpha1.CephDeploymentSecretList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("cephdeploymentsecrets"),
			v1alpha1.SchemeGroupVersion.WithKind("CephDeploymentSecret"),
			func() *v1alpha1.CephDeploymentSecret { return &v1alpha1.CephDeploymentSecret{} },
			func() *v1alpha1.CephDeploymentSecretList { return &v1alpha1.CephDeploymentSecretList{} },
			func(dst, src *v1alpha1.CephDeploymentSecretList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.CephDeploymentSecretList) []*v1alpha1.CephDeploymentSecret {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.CephDeploymentSecretList, items []*v1alpha1.CephDeploymentSecret) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
