/*
Copyright 2026 Mirantis IT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/Mirantis/pelagia/pkg/apis/ceph.pelagia.lcm/v1alpha1"
	cephpelagialcmv1alpha1 "github.com/Mirantis/pelagia/pkg/client/clientset/versioned/typed/ceph.pelagia.lcm/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCephDeploymentHealths implements CephDeploymentHealthInterface
type fakeCephDeploymentHealths struct {
	*gentype.FakeClientWithList[*v1alpha1.CephDeploymentHealth, *v1alpha1.CephDeploymentHealthList]
	Fake *FakeLcmV1alpha1
}

func newFakeCephDeploymentHealths(fake *FakeLcmV1alpha1, namespace string) cephpelagialcmv1alpha1.CephDeploymentHealthInterface {
	return &fakeCephDeploymentHealths{
		gentype.NewFakeClientWithList[*v1alpha1.CephDeploymentHealth, *v1alpha1.CephDeploymentHealthList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("cephdeploymenthealths"),
			v1alpha1.SchemeGroupVersion.WithKind("CephDeploymentHealth"),
			func() *v1alpha1.CephDeploymentHealth { return &v1alpha1.CephDeploymentHealth{} },
			func() *v1alpha1.CephDeploymentHealthList { return &v1alpha1.CephDeploymentHealthList{} },
			func(dst, src *v1alpha1.CephDeploymentHealthList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.CephDeploymentHealthList) []*v1alpha1.CephDeploymentHealth {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.CephDeploymentHealthList, items []*v1alpha1.CephDeploymentHealth) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
