{{ if .Values.rookConfig.configureRook }}
# OLM: BEGIN CSI RBD CLUSTER ROLEBINDING
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-csi-nodeplugin
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: rook-csi-rbd-plugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
roleRef:
  kind: ClusterRole
  name: rbd-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-csi-provisioner-role
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: rook-csi-rbd-provisioner-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
roleRef:
  kind: ClusterRole
  name: rbd-external-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
# OLM: END CSI RBD CLUSTER ROLEBINDING
# OLM: BEGIN OBJECTBUCKET ROLEBINDING
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-object-bucket
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-object-bucket
subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: {{ .Values.rookConfig.rookNamespace }}
# OLM: END OBJECTBUCKET ROLEBINDING
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-ceph-system
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-system
subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
# Grant the rook system daemons cluster-wide access to manage the Rook CRDs, PVCs, and storage classes
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-global
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-global
subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: {{ .Values.rookConfig.rookNamespace }}
# OLM: END OPERATOR ROLEBINDING
---
# Allow the ceph mgr to access cluster-wide resources necessary for the mgr modules
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-mgr-cluster
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr-cluster
subjects:
  - kind: ServiceAccount
    name: rook-ceph-mgr
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
# Allow the ceph osd to access cluster-wide resources necessary for determining their topology location
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-osd
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-osd
subjects:
  - kind: ServiceAccount
    name: rook-ceph-osd
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-csi-provisioner-role
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: rook-csi-cephfs-provisioner-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
roleRef:
  kind: ClusterRole
  name: cephfs-external-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
# OLM: END CSI CEPHFS CLUSTER ROLEBINDING
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-csi-nodeplugin-role
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: rook-csi-cephfs-plugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
roleRef:
  kind: ClusterRole
  name: cephfs-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ceph-nfs-csi-provisioner-role
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: rook-csi-nfs-provisioner-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
roleRef:
  kind: ClusterRole
  name: ceph-nfs-external-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ceph-nfs-csi-nodeplugin-role
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: rook-csi-nfs-plugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
roleRef:
  kind: ClusterRole
  name: ceph-nfs-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
---
# RBAC for ceph cosi driver service account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-provisioner-role-binding
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ceph
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: objectstorage-provisioner
    namespace: {{ .Values.rookConfig.rookNamespace }}
roleRef:
  kind: ClusterRole
  name: objectstorage-provisioner-role
  apiGroup: rbac.authorization.k8s.io
  {{- if eq .Values.productSetup "mke" }}
---
# required for MKE since rook operator makes action around pods/deploys/replicas
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
  name: {{ .Values.rookConfig.rookNamespace }}-rook-ceph:cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: {{ .Values.rookConfig.rookNamespace }}
  - kind: ServiceAccount
    name: rook-ceph-mgr
    namespace: {{ .Values.rookConfig.rookNamespace }}
  {{- end }}
{{- end }}
