{{ if .Values.rookConfig.configureRook }}
---
# Grant the operator, agent, and discovery agents access to resources in the namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-system
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-system
subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: {{ .Values.rookConfig.rookNamespace }}
# OLM: BEGIN CLUSTER ROLEBINDING
---
# Allow the osd pods in this namespace to work with configmaps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-osd
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-osd
subjects:
  - kind: ServiceAccount
    name: rook-ceph-osd
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
# Allow the ceph mgr to access the cluster-specific resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-mgr
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-mgr
subjects:
  - kind: ServiceAccount
    name: rook-ceph-mgr
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
# Allow the ceph mgr to access the rook system resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-mgr-system
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr-system
subjects:
  - kind: ServiceAccount
    name: rook-ceph-mgr
    namespace: {{ .Values.rookConfig.rookNamespace }}
# OLM: END CLUSTER ROLEBINDING
# OLM: BEGIN CMD REPORTER ROLEBINDING
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-cmd-reporter
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-cmd-reporter
subjects:
  - kind: ServiceAccount
    name: rook-ceph-cmd-reporter
    namespace: {{ .Values.rookConfig.rookNamespace }}
# OLM: END CMD REPORTER ROLEBINDING
# OLM: BEGIN PURGE OSD ROLEBINDING
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-purge-osd
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-purge-osd
subjects:
  - kind: ServiceAccount
    name: rook-ceph-purge-osd
    namespace: {{ .Values.rookConfig.rookNamespace }}
# OLM: END PURGE OSD ROLEBINDING
# OLM: BEGIN CSI CEPHFS ROLEBINDING
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-csi-provisioner-role-cfg
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: rook-csi-cephfs-provisioner-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
roleRef:
  kind: Role
  name: cephfs-external-provisioner-cfg
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-csi-nodeplugin-role-cfg
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: rook-csi-cephfs-provisioner-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
  - kind: ServiceAccount
    name: rook-csi-cephfs-plugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
roleRef:
  kind: Role
  name: cephfs-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
# OLM: END CSI CEPHFS ROLEBINDING
# OLM: BEGIN CSI RBD ROLEBINDING
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-csi-provisioner-role-cfg
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: rook-csi-rbd-provisioner-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
roleRef:
  kind: Role
  name: rbd-external-provisioner-cfg
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbd-csi-nodeplugin-role-cfg
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: rook-csi-rbd-plugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
roleRef:
  kind: Role
  name: rbd-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
# OLM: END CSI RBD ROLEBINDING
---
# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-cluster-mgmt
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: {{ .Values.rookConfig.rookNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-cluster-mgmt
{{- end }}
