{{ if .Values.rookConfig.configureRook }}
# Start base cluster service accounts
---
# Service account for Ceph OSDs
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-osd
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for Ceph mgrs
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-mgr
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for the job that reports the Ceph version in an image
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-cmd-reporter
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for job that purges OSDs from a Rook-Ceph cluster
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-purge-osd
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for RGW server
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-rgw
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for other components
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-default
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for NVMe-oF gateway
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-nvmeof
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
# End base cluster service accounts
#
# Service account for the Rook-Ceph operator
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-system
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for the CephFS CSI driver
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-cephfs-plugin-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
{{- if .Values.rookConfig.csiNfsEnabled }}
---
# Service account for the NFS CSI driver
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-nfs-plugin-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for the NFS CSI provisioner
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-nfs-provisioner-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
{{- end }}
---
# Service account for the CephFS CSI provisioner
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-cephfs-provisioner-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for the RBD CSI driver
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-rbd-plugin-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for the RBD CSI provisioner
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-rbd-provisioner-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for Ceph COSI driver
kind: ServiceAccount
apiVersion: v1
metadata:
  name: objectstorage-provisioner
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ceph
    app.kubernetes.io/name: cosi-driver-ceph
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
{{- end }}
