{{ if .Values.rookConfig.configureRook }}
---
# OLM: BEGIN SERVICE ACCOUNT SYSTEM
# The rook system service account used by the operator, agent, and discovery pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-system
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
# OLM: END SERVICE ACCOUNT SYSTEM
# OLM: BEGIN SERVICE ACCOUNT OSD
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-osd
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
# OLM: END SERVICE ACCOUNT OSD
# OLM: BEGIN SERVICE ACCOUNT MGR
---
# Service account for the Ceph Mgr. Must exist and cannot be renamed.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-mgr
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
# OLM: END SERVICE ACCOUNT MGR
# OLM: BEGIN CMD REPORTER SERVICE ACCOUNT
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-cmd-reporter
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
# OLM: END CMD REPORTER SERVICE ACCOUNT
# OLM: BEGIN PURGE OSD SERVICE ACCOUNT
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-purge-osd
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
# OLM: END PURGE OSD SERVICE ACCOUNT
# OLM: BEGIN RGW SERVICE ACCOUNT
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-rgw
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
# OLM: END RGW SERVICE ACCOUNT
# OLM: BEGIN CSI CEPHFS SERVICE ACCOUNT
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-cephfs-plugin-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-cephfs-provisioner-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
# OLM: END CSI CEPHFS SERVICE ACCOUNT
# OLM: BEGIN CSI RBD SERVICE ACCOUNT
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-rbd-plugin-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-rbd-provisioner-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
# OLM: END CSI RBD SERVICE ACCOUNT
---
# Service account for the NFS CSI driver
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-nfs-plugin-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for the NFS CSI provisioner
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-nfs-provisioner-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
# Service account for Ceph COSI driver
apiVersion: v1
kind: ServiceAccount
metadata:
  name: objectstorage-provisioner
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ceph
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-default
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "rook.labels" . | indent 4 }}
{{ include "chart.labels" . | indent 4 }}
{{- end }}
