/*
Copyright 2026 Mirantis IT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	cephpelagialcmv1alpha1 "github.com/Mirantis/pelagia/pkg/apis/ceph.pelagia.lcm/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CephOsdRemoveTaskLister helps list CephOsdRemoveTasks.
// All objects returned here must be treated as read-only.
type CephOsdRemoveTaskLister interface {
	// List lists all CephOsdRemoveTasks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cephpelagialcmv1alpha1.CephOsdRemoveTask, err error)
	// CephOsdRemoveTasks returns an object that can list and get CephOsdRemoveTasks.
	CephOsdRemoveTasks(namespace string) CephOsdRemoveTaskNamespaceLister
	CephOsdRemoveTaskListerExpansion
}

// cephOsdRemoveTaskLister implements the CephOsdRemoveTaskLister interface.
type cephOsdRemoveTaskLister struct {
	listers.ResourceIndexer[*cephpelagialcmv1alpha1.CephOsdRemoveTask]
}

// NewCephOsdRemoveTaskLister returns a new CephOsdRemoveTaskLister.
func NewCephOsdRemoveTaskLister(indexer cache.Indexer) CephOsdRemoveTaskLister {
	return &cephOsdRemoveTaskLister{listers.New[*cephpelagialcmv1alpha1.CephOsdRemoveTask](indexer, cephpelagialcmv1alpha1.Resource("cephosdremovetask"))}
}

// CephOsdRemoveTasks returns an object that can list and get CephOsdRemoveTasks.
func (s *cephOsdRemoveTaskLister) CephOsdRemoveTasks(namespace string) CephOsdRemoveTaskNamespaceLister {
	return cephOsdRemoveTaskNamespaceLister{listers.NewNamespaced[*cephpelagialcmv1alpha1.CephOsdRemoveTask](s.ResourceIndexer, namespace)}
}

// CephOsdRemoveTaskNamespaceLister helps list and get CephOsdRemoveTasks.
// All objects returned here must be treated as read-only.
type CephOsdRemoveTaskNamespaceLister interface {
	// List lists all CephOsdRemoveTasks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cephpelagialcmv1alpha1.CephOsdRemoveTask, err error)
	// Get retrieves the CephOsdRemoveTask from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*cephpelagialcmv1alpha1.CephOsdRemoveTask, error)
	CephOsdRemoveTaskNamespaceListerExpansion
}

// cephOsdRemoveTaskNamespaceLister implements the CephOsdRemoveTaskNamespaceLister
// interface.
type cephOsdRemoveTaskNamespaceLister struct {
	listers.ResourceIndexer[*cephpelagialcmv1alpha1.CephOsdRemoveTask]
}
