/*
Copyright 2026 Mirantis IT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CephDeploymentListerExpansion allows custom methods to be added to
// CephDeploymentLister.
type CephDeploymentListerExpansion interface{}

// CephDeploymentNamespaceListerExpansion allows custom methods to be added to
// CephDeploymentNamespaceLister.
type CephDeploymentNamespaceListerExpansion interface{}

// CephDeploymentHealthListerExpansion allows custom methods to be added to
// CephDeploymentHealthLister.
type CephDeploymentHealthListerExpansion interface{}

// CephDeploymentHealthNamespaceListerExpansion allows custom methods to be added to
// CephDeploymentHealthNamespaceLister.
type CephDeploymentHealthNamespaceListerExpansion interface{}

// CephDeploymentMaintenanceListerExpansion allows custom methods to be added to
// CephDeploymentMaintenanceLister.
type CephDeploymentMaintenanceListerExpansion interface{}

// CephDeploymentMaintenanceNamespaceListerExpansion allows custom methods to be added to
// CephDeploymentMaintenanceNamespaceLister.
type CephDeploymentMaintenanceNamespaceListerExpansion interface{}

// CephDeploymentSecretListerExpansion allows custom methods to be added to
// CephDeploymentSecretLister.
type CephDeploymentSecretListerExpansion interface{}

// CephDeploymentSecretNamespaceListerExpansion allows custom methods to be added to
// CephDeploymentSecretNamespaceLister.
type CephDeploymentSecretNamespaceListerExpansion interface{}

// CephOsdRemoveTaskListerExpansion allows custom methods to be added to
// CephOsdRemoveTaskLister.
type CephOsdRemoveTaskListerExpansion interface{}

// CephOsdRemoveTaskNamespaceListerExpansion allows custom methods to be added to
// CephOsdRemoveTaskNamespaceLister.
type CephOsdRemoveTaskNamespaceListerExpansion interface{}
