apiVersion: v2
appVersion: dev
description: A Helm chart to deploy Ceph Pelagia resources
name: pelagia-ceph
version: 1.0.0
maintainers:
- name: Mirantis Inc.
  url: https://github.com/Mirantis/pelagia
dependencies:
- name: ceph-csi-operator
  repository: file://charts/ceph-csi-operator
  condition: ceph-csi-operator.enabled
  version: 1.0.0
  tags:
    - csi
- name: rook
  repository: file://charts/rook
  condition: rook.enabled
  version: 1.0.0
  import-values:
    - child: images.operator
      parent: images.rook
  tags:
    - rook
- name: snapshot-controller
  repository: file://charts/snapshot-controller
  condition: snapshot-controller.enabled
  version: 1.0.0
  tags:
    - snapshot-controller
