global:
  dockerBaseUrl: registry.mirantis.com
  clusterRelease: ""
  namespace: ""

productSetup: "mke"
cephDeployment:
  enabled: true
  netpolEnabled: &netpolEnabled true
  installSharedNamespace: true
  openstackSharedNamespace: openstack-ceph-shared
  # drain request and readiness label keys
  drainRequestLabelKey: ""
  drainReadyLabelKey: ""
lcmConfig:
  rookNamespace: &rookNamespace rook-ceph
  rgwPublicAccessServiceSelector: "external_access=rgw"
  diskDaemonPortParameter: 9999
  diskDaemonNodeSelector: "ceph_role_osd=true"
  cephDaemonsetLabelExclude: ""
  # if gateway api is not required or not supported - should be disabled
  gatewayAPIEnabled: true
  gatewayName: ""
  gatewayNamespace: ""
  # useIngress used only for backward compatibility with ingress deprecation
  # if no ingress required - set to false
  useIngress: true

controllers:
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
  securityContextControllers:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
  livenessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - pidof pelagia-ceph
    failureThreshold: 3
    periodSeconds: 10
    initialDelaySeconds: 5
  readinessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - pidof pelagia-ceph
    failureThreshold: 3
    periodSeconds: 10
  cephdeployment:
    appName: pelagia-deployment-controller
    account:
      name: pelagia-deployment-account
      clusterRole: pelagia-deployment-role-cluster
      role: pelagia-deployment-role
    controllers:
      deployment:
        name: pelagia-deployment-controller
        leaderElectionID: pelagia-deployment-controller-leader-election
      secret:
        name: pelagia-secret-controller
        leaderElectionID: pelagia-secret-controller-leader-election
    replicas: 3
  lcm:
    appName: pelagia-lcm-controller
    account:
      name: pelagia-lcm-account
      clusterRole: pelagia-lcm-role-cluster
      role: pelagia-lcm-role
    controllers:
      health:
        name: pelagia-health-controller
        leaderElectionID: pelagia-health-controller-leader-election
      infra:
        name: pelagia-infra-controller
        leaderElectionID: pelagia-infra-controller-leader-election
      osdremove:
        name: pelagia-osdremove-task-controller
        leaderElectionID: pelagia-osdremove-task-controller-leader-election
    replicas: 3

# cephRelease is ceph version name, i.e. tentacle, squid etc. Empty means latest supported.
cephRelease: ""
images:
  pelagia:
    repository: pelagia/pelagia
    tag: latest
    # fullName is mostly used for test purposes
    fullName: ""
    pullPolicy: Always
  ceph:
    repository: pelagia/ceph
    tag:
      latest: &latestImageCeph v20.2.2-2.release
      squid: v19.2.4-3.cve
      tentacle: *latestImageCeph

snapshot-controller:
  enabled: true

ceph-csi-operator:
  enabled: true
  csiOperatorConfig:
    rookNamespace: *rookNamespace

rook:
  enabled: true
  rookConfig:
    rookNamespace: *rookNamespace
    netpolEnabled: *netpolEnabled
