/*
Copyright 2026 Mirantis IT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	cephpelagialcmv1alpha1 "github.com/Mirantis/pelagia/pkg/apis/ceph.pelagia.lcm/v1alpha1"
	scheme "github.com/Mirantis/pelagia/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CephDeploymentMaintenancesGetter has a method to return a CephDeploymentMaintenanceInterface.
// A group's client should implement this interface.
type CephDeploymentMaintenancesGetter interface {
	CephDeploymentMaintenances(namespace string) CephDeploymentMaintenanceInterface
}

// CephDeploymentMaintenanceInterface has methods to work with CephDeploymentMaintenance resources.
type CephDeploymentMaintenanceInterface interface {
	Create(ctx context.Context, cephDeploymentMaintenance *cephpelagialcmv1alpha1.CephDeploymentMaintenance, opts v1.CreateOptions) (*cephpelagialcmv1alpha1.CephDeploymentMaintenance, error)
	Update(ctx context.Context, cephDeploymentMaintenance *cephpelagialcmv1alpha1.CephDeploymentMaintenance, opts v1.UpdateOptions) (*cephpelagialcmv1alpha1.CephDeploymentMaintenance, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, cephDeploymentMaintenance *cephpelagialcmv1alpha1.CephDeploymentMaintenance, opts v1.UpdateOptions) (*cephpelagialcmv1alpha1.CephDeploymentMaintenance, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*cephpelagialcmv1alpha1.CephDeploymentMaintenance, error)
	List(ctx context.Context, opts v1.ListOptions) (*cephpelagialcmv1alpha1.CephDeploymentMaintenanceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *cephpelagialcmv1alpha1.CephDeploymentMaintenance, err error)
	CephDeploymentMaintenanceExpansion
}

// cephDeploymentMaintenances implements CephDeploymentMaintenanceInterface
type cephDeploymentMaintenances struct {
	*gentype.ClientWithList[*cephpelagialcmv1alpha1.CephDeploymentMaintenance, *cephpelagialcmv1alpha1.CephDeploymentMaintenanceList]
}

// newCephDeploymentMaintenances returns a CephDeploymentMaintenances
func newCephDeploymentMaintenances(c *LcmV1alpha1Client, namespace string) *cephDeploymentMaintenances {
	return &cephDeploymentMaintenances{
		gentype.NewClientWithList[*cephpelagialcmv1alpha1.CephDeploymentMaintenance, *cephpelagialcmv1alpha1.CephDeploymentMaintenanceList](
			"cephdeploymentmaintenances",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *cephpelagialcmv1alpha1.CephDeploymentMaintenance {
				return &cephpelagialcmv1alpha1.CephDeploymentMaintenance{}
			},
			func() *cephpelagialcmv1alpha1.CephDeploymentMaintenanceList {
				return &cephpelagialcmv1alpha1.CephDeploymentMaintenanceList{}
			},
		),
	}
}
