/*
Copyright 2025 Mirantis IT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/Mirantis/pelagia/pkg/apis/ceph.pelagia.lcm/v1alpha1"
	scheme "github.com/Mirantis/pelagia/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CephDeploymentHealthsGetter has a method to return a CephDeploymentHealthInterface.
// A group's client should implement this interface.
type CephDeploymentHealthsGetter interface {
	CephDeploymentHealths(namespace string) CephDeploymentHealthInterface
}

// CephDeploymentHealthInterface has methods to work with CephDeploymentHealth resources.
type CephDeploymentHealthInterface interface {
	Create(ctx context.Context, cephDeploymentHealth *v1alpha1.CephDeploymentHealth, opts v1.CreateOptions) (*v1alpha1.CephDeploymentHealth, error)
	Update(ctx context.Context, cephDeploymentHealth *v1alpha1.CephDeploymentHealth, opts v1.UpdateOptions) (*v1alpha1.CephDeploymentHealth, error)
	UpdateStatus(ctx context.Context, cephDeploymentHealth *v1alpha1.CephDeploymentHealth, opts v1.UpdateOptions) (*v1alpha1.CephDeploymentHealth, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CephDeploymentHealth, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CephDeploymentHealthList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CephDeploymentHealth, err error)
	CephDeploymentHealthExpansion
}

// cephDeploymentHealths implements CephDeploymentHealthInterface
type cephDeploymentHealths struct {
	client rest.Interface
	ns     string
}

// newCephDeploymentHealths returns a CephDeploymentHealths
func newCephDeploymentHealths(c *LcmV1alpha1Client, namespace string) *cephDeploymentHealths {
	return &cephDeploymentHealths{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cephDeploymentHealth, and returns the corresponding cephDeploymentHealth object, and an error if there is any.
func (c *cephDeploymentHealths) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CephDeploymentHealth, err error) {
	result = &v1alpha1.CephDeploymentHealth{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cephdeploymenthealths").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CephDeploymentHealths that match those selectors.
func (c *cephDeploymentHealths) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CephDeploymentHealthList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CephDeploymentHealthList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cephdeploymenthealths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cephDeploymentHealths.
func (c *cephDeploymentHealths) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cephdeploymenthealths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a cephDeploymentHealth and creates it.  Returns the server's representation of the cephDeploymentHealth, and an error, if there is any.
func (c *cephDeploymentHealths) Create(ctx context.Context, cephDeploymentHealth *v1alpha1.CephDeploymentHealth, opts v1.CreateOptions) (result *v1alpha1.CephDeploymentHealth, err error) {
	result = &v1alpha1.CephDeploymentHealth{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cephdeploymenthealths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cephDeploymentHealth).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a cephDeploymentHealth and updates it. Returns the server's representation of the cephDeploymentHealth, and an error, if there is any.
func (c *cephDeploymentHealths) Update(ctx context.Context, cephDeploymentHealth *v1alpha1.CephDeploymentHealth, opts v1.UpdateOptions) (result *v1alpha1.CephDeploymentHealth, err error) {
	result = &v1alpha1.CephDeploymentHealth{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cephdeploymenthealths").
		Name(cephDeploymentHealth.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cephDeploymentHealth).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *cephDeploymentHealths) UpdateStatus(ctx context.Context, cephDeploymentHealth *v1alpha1.CephDeploymentHealth, opts v1.UpdateOptions) (result *v1alpha1.CephDeploymentHealth, err error) {
	result = &v1alpha1.CephDeploymentHealth{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cephdeploymenthealths").
		Name(cephDeploymentHealth.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cephDeploymentHealth).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the cephDeploymentHealth and deletes it. Returns an error if one occurs.
func (c *cephDeploymentHealths) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cephdeploymenthealths").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cephDeploymentHealths) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cephdeploymenthealths").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched cephDeploymentHealth.
func (c *cephDeploymentHealths) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CephDeploymentHealth, err error) {
	result = &v1alpha1.CephDeploymentHealth{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cephdeploymenthealths").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
