/*
Copyright 2026 Mirantis IT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	cephpelagialcmv1alpha1 "github.com/Mirantis/pelagia/pkg/apis/ceph.pelagia.lcm/v1alpha1"
	scheme "github.com/Mirantis/pelagia/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CephDeploymentSecretsGetter has a method to return a CephDeploymentSecretInterface.
// A group's client should implement this interface.
type CephDeploymentSecretsGetter interface {
	CephDeploymentSecrets(namespace string) CephDeploymentSecretInterface
}

// CephDeploymentSecretInterface has methods to work with CephDeploymentSecret resources.
type CephDeploymentSecretInterface interface {
	Create(ctx context.Context, cephDeploymentSecret *cephpelagialcmv1alpha1.CephDeploymentSecret, opts v1.CreateOptions) (*cephpelagialcmv1alpha1.CephDeploymentSecret, error)
	Update(ctx context.Context, cephDeploymentSecret *cephpelagialcmv1alpha1.CephDeploymentSecret, opts v1.UpdateOptions) (*cephpelagialcmv1alpha1.CephDeploymentSecret, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, cephDeploymentSecret *cephpelagialcmv1alpha1.CephDeploymentSecret, opts v1.UpdateOptions) (*cephpelagialcmv1alpha1.CephDeploymentSecret, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*cephpelagialcmv1alpha1.CephDeploymentSecret, error)
	List(ctx context.Context, opts v1.ListOptions) (*cephpelagialcmv1alpha1.CephDeploymentSecretList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *cephpelagialcmv1alpha1.CephDeploymentSecret, err error)
	CephDeploymentSecretExpansion
}

// cephDeploymentSecrets implements CephDeploymentSecretInterface
type cephDeploymentSecrets struct {
	*gentype.ClientWithList[*cephpelagialcmv1alpha1.CephDeploymentSecret, *cephpelagialcmv1alpha1.CephDeploymentSecretList]
}

// newCephDeploymentSecrets returns a CephDeploymentSecrets
func newCephDeploymentSecrets(c *LcmV1alpha1Client, namespace string) *cephDeploymentSecrets {
	return &cephDeploymentSecrets{
		gentype.NewClientWithList[*cephpelagialcmv1alpha1.CephDeploymentSecret, *cephpelagialcmv1alpha1.CephDeploymentSecretList](
			"cephdeploymentsecrets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *cephpelagialcmv1alpha1.CephDeploymentSecret {
				return &cephpelagialcmv1alpha1.CephDeploymentSecret{}
			},
			func() *cephpelagialcmv1alpha1.CephDeploymentSecretList {
				return &cephpelagialcmv1alpha1.CephDeploymentSecretList{}
			},
		),
	}
}
