/*
Copyright 2026 Mirantis IT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	cephpelagialcmv1alpha1 "github.com/Mirantis/pelagia/pkg/apis/ceph.pelagia.lcm/v1alpha1"
	scheme "github.com/Mirantis/pelagia/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type LcmV1alpha1Interface interface {
	RESTClient() rest.Interface
	CephDeploymentsGetter
	CephDeploymentHealthsGetter
	CephDeploymentMaintenancesGetter
	CephDeploymentSecretsGetter
	CephOsdRemoveTasksGetter
}

// LcmV1alpha1Client is used to interact with features provided by the lcm.mirantis.com group.
type LcmV1alpha1Client struct {
	restClient rest.Interface
}

func (c *LcmV1alpha1Client) CephDeployments(namespace string) CephDeploymentInterface {
	return newCephDeployments(c, namespace)
}

func (c *LcmV1alpha1Client) CephDeploymentHealths(namespace string) CephDeploymentHealthInterface {
	return newCephDeploymentHealths(c, namespace)
}

func (c *LcmV1alpha1Client) CephDeploymentMaintenances(namespace string) CephDeploymentMaintenanceInterface {
	return newCephDeploymentMaintenances(c, namespace)
}

func (c *LcmV1alpha1Client) CephDeploymentSecrets(namespace string) CephDeploymentSecretInterface {
	return newCephDeploymentSecrets(c, namespace)
}

func (c *LcmV1alpha1Client) CephOsdRemoveTasks(namespace string) CephOsdRemoveTaskInterface {
	return newCephOsdRemoveTasks(c, namespace)
}

// NewForConfig creates a new LcmV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*LcmV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new LcmV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*LcmV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &LcmV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new LcmV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *LcmV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new LcmV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *LcmV1alpha1Client {
	return &LcmV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := cephpelagialcmv1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *LcmV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
